name: fair_compiler
description: A complier which can generate Fair bundle for widget with annotation.
version: 0.3.0+1
homepage: https://fair.58.com/

environment:
  sdk: '>=2.12.0-0 <3.0.0'

#executables:
#  fairc:
dependencies:
  source_gen: ^1.2.0
  build: ^2.1.1
  crypto: ^3.0.0
  build_config: ^1.0.0
  process: ^4.2.4
  archive: ^3.1.6
  intl: ^0.16.1
  path: ^1.8.0
  analyzer: ^2.8.0
  dart_style: ^2.2.0
  glob: ^2.0.0
  pedantic: ^1.8.0
#  file: ^5.0.0
#  fair_annotation: ^0.2.0
  fair_annotation:
    path: ../annotation
  http: ^0.13.4
  fairc:
    path: ../dart2dsl
  dartToJs:
    path: ../dart2js

dev_dependencies:
  test: ^1.6.0
