name: fairc
description: A sample command-line application.
# version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.7.0 <3.0.0'
executables:
  fairc:
dependencies:
  analyzer: ^2.8.0


dev_dependencies:
  pedantic: ^1.8.0
  test: ^1.6.0
  source_gen: ^0.9.7+1
  build_runner: ^1.4.0